#pragma once
// see explanaition on:
// http://gernotklingler.com/blog/creating-using-shared-libraries-different-compilers-different-operating-systems/
#include "mylibA-shared-exports.h"  // automatically generated by cmake
                                   // by the generate_export_header() macro

/* Make this header file easier to include in C++ code */
#ifdef __cplusplus
extern "C" {
#endif

mylibA_EXPORTS_DEFINE int doTheMath(int a, int b);

#ifdef __cplusplus
}
#endif
